//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Animations/Player/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Animations/Player/PlayerInputActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerInputControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerInputControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""PlayerKeyboardInput"",
            ""id"": ""0e1526e8-8611-41c0-82fd-cb06fe27e357"",
            ""actions"": [
                {
                    ""name"": ""SwitchWeapon_1"",
                    ""type"": ""Button"",
                    ""id"": ""1a9ce4bf-104a-4977-a9a4-56eba4ba4f1c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchWeapon_2"",
                    ""type"": ""Button"",
                    ""id"": ""8ec81df6-40e4-40b6-bee3-f10690bca733"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""63294603-6b03-4f3b-aee7-5f507785bc98"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchWeapon_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46b804d2-dea6-4dd3-8d8c-c425e9434107"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchWeapon_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerKeyboardInput
        m_PlayerKeyboardInput = asset.FindActionMap("PlayerKeyboardInput", throwIfNotFound: true);
        m_PlayerKeyboardInput_SwitchWeapon_1 = m_PlayerKeyboardInput.FindAction("SwitchWeapon_1", throwIfNotFound: true);
        m_PlayerKeyboardInput_SwitchWeapon_2 = m_PlayerKeyboardInput.FindAction("SwitchWeapon_2", throwIfNotFound: true);
    }

    ~@PlayerInputControls()
    {
        UnityEngine.Debug.Assert(!m_PlayerKeyboardInput.enabled, "This will cause a leak and performance issues, PlayerInputControls.PlayerKeyboardInput.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerKeyboardInput
    private readonly InputActionMap m_PlayerKeyboardInput;
    private List<IPlayerKeyboardInputActions> m_PlayerKeyboardInputActionsCallbackInterfaces = new List<IPlayerKeyboardInputActions>();
    private readonly InputAction m_PlayerKeyboardInput_SwitchWeapon_1;
    private readonly InputAction m_PlayerKeyboardInput_SwitchWeapon_2;
    /// <summary>
    /// Provides access to input actions defined in input action map "PlayerKeyboardInput".
    /// </summary>
    public struct PlayerKeyboardInputActions
    {
        private @PlayerInputControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerKeyboardInputActions(@PlayerInputControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerKeyboardInput/SwitchWeapon_1".
        /// </summary>
        public InputAction @SwitchWeapon_1 => m_Wrapper.m_PlayerKeyboardInput_SwitchWeapon_1;
        /// <summary>
        /// Provides access to the underlying input action "PlayerKeyboardInput/SwitchWeapon_2".
        /// </summary>
        public InputAction @SwitchWeapon_2 => m_Wrapper.m_PlayerKeyboardInput_SwitchWeapon_2;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerKeyboardInput; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerKeyboardInputActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerKeyboardInputActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerKeyboardInputActions" />
        public void AddCallbacks(IPlayerKeyboardInputActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerKeyboardInputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerKeyboardInputActionsCallbackInterfaces.Add(instance);
            @SwitchWeapon_1.started += instance.OnSwitchWeapon_1;
            @SwitchWeapon_1.performed += instance.OnSwitchWeapon_1;
            @SwitchWeapon_1.canceled += instance.OnSwitchWeapon_1;
            @SwitchWeapon_2.started += instance.OnSwitchWeapon_2;
            @SwitchWeapon_2.performed += instance.OnSwitchWeapon_2;
            @SwitchWeapon_2.canceled += instance.OnSwitchWeapon_2;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerKeyboardInputActions" />
        private void UnregisterCallbacks(IPlayerKeyboardInputActions instance)
        {
            @SwitchWeapon_1.started -= instance.OnSwitchWeapon_1;
            @SwitchWeapon_1.performed -= instance.OnSwitchWeapon_1;
            @SwitchWeapon_1.canceled -= instance.OnSwitchWeapon_1;
            @SwitchWeapon_2.started -= instance.OnSwitchWeapon_2;
            @SwitchWeapon_2.performed -= instance.OnSwitchWeapon_2;
            @SwitchWeapon_2.canceled -= instance.OnSwitchWeapon_2;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerKeyboardInputActions.UnregisterCallbacks(IPlayerKeyboardInputActions)" />.
        /// </summary>
        /// <seealso cref="PlayerKeyboardInputActions.UnregisterCallbacks(IPlayerKeyboardInputActions)" />
        public void RemoveCallbacks(IPlayerKeyboardInputActions instance)
        {
            if (m_Wrapper.m_PlayerKeyboardInputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerKeyboardInputActions.AddCallbacks(IPlayerKeyboardInputActions)" />
        /// <seealso cref="PlayerKeyboardInputActions.RemoveCallbacks(IPlayerKeyboardInputActions)" />
        /// <seealso cref="PlayerKeyboardInputActions.UnregisterCallbacks(IPlayerKeyboardInputActions)" />
        public void SetCallbacks(IPlayerKeyboardInputActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerKeyboardInputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerKeyboardInputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerKeyboardInputActions" /> instance referencing this action map.
    /// </summary>
    public PlayerKeyboardInputActions @PlayerKeyboardInput => new PlayerKeyboardInputActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PlayerKeyboardInput" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerKeyboardInputActions.AddCallbacks(IPlayerKeyboardInputActions)" />
    /// <seealso cref="PlayerKeyboardInputActions.RemoveCallbacks(IPlayerKeyboardInputActions)" />
    public interface IPlayerKeyboardInputActions
    {
        /// <summary>
        /// Method invoked when associated input action "SwitchWeapon_1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSwitchWeapon_1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SwitchWeapon_2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSwitchWeapon_2(InputAction.CallbackContext context);
    }
}
